#████████╗██╗███╗░░░███╗░█████╗░  ░█████╗░███╗░░██╗████████╗██╗  ░█████╗░██╗░░██╗███████╗░█████╗░████████╗
#╚══██╔══╝██║████╗░████║██╔══██╗  ██╔══██╗████╗░██║╚══██╔══╝██║  ██╔══██╗██║░░██║██╔════╝██╔══██╗╚══██╔══╝
#░░░██║░░░██║██╔████╔██║███████║  ███████║██╔██╗██║░░░██║░░░██║  ██║░░╚═╝███████║█████╗░░███████║░░░██║░░░
#░░░██║░░░██║██║╚██╔╝██║██╔══██║  ██╔══██║██║╚████║░░░██║░░░██║  ██║░░██╗██╔══██║██╔══╝░░██╔══██║░░░██║░░░
#░░░██║░░░██║██║░╚═╝░██║██║░░██║  ██║░░██║██║░╚███║░░░██║░░░██║  ╚█████╔╝██║░░██║███████╗██║░░██║░░░██║░░░
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝  ╚═╝░░╚═╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝  ░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#
#место в которое будет телепортироваться игрок для проверки на читы
world: "world"
x: 184
y: 76
z: 207
#
#настройка сообщений
title: "здарова еблан"
subtitle: "это проверка на читы"
chatmessage: "напиши в чат: (я не читер мамой клянусь!) для прохождения проверки на читы"
confirm-message: "я не читер мамой клянусь!"
verification-passed: "спасибо за прохождение проверки! пошел нахуй <3"
#
#время в секундах для интервала отправки сообщения chatmessage
chatmessage-time-interval: 5
#
#настройка тайтла
fadein: 10
stay: 70
fadeout: 20
#
#thanks for use my plugin <3